
with-expecter: true
filename: "mock_{{.InterfaceName | lower }}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}mocks"
packages:
  github.com/kriuchkov/tonbeacon/core/ports:
    interfaces:
      WalletPort:
      DatabasePort:
      DatabaseTransactionPort:
      OutboxMessagePort:
      