// Code generated by mockery v2.52.3. DO NOT EDIT.

package portsmocks

import (
	context "context"

	model "github.com/kriuchkov/tonbeacon/internal/core/model"
	mock "github.com/stretchr/testify/mock"
)

// MockDatabasePort is an autogenerated mock type for the DatabasePort type
type MockDatabasePort struct {
	mock.Mock
}

type MockDatabasePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabasePort) EXPECT() *MockDatabasePort_Expecter {
	return &MockDatabasePort_Expecter{mock: &_m.Mock}
}

// InsertAccount provides a mock function with given fields: ctx, accountID
func (_m *MockDatabasePort) InsertAccount(ctx context.Context, accountID string) (*model.Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for InsertAccount")
	}

	var r0 *model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabasePort_InsertAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAccount'
type MockDatabasePort_InsertAccount_Call struct {
	*mock.Call
}

// InsertAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockDatabasePort_Expecter) InsertAccount(ctx interface{}, accountID interface{}) *MockDatabasePort_InsertAccount_Call {
	return &MockDatabasePort_InsertAccount_Call{Call: _e.mock.On("InsertAccount", ctx, accountID)}
}

func (_c *MockDatabasePort_InsertAccount_Call) Run(run func(ctx context.Context, accountID string)) *MockDatabasePort_InsertAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabasePort_InsertAccount_Call) Return(_a0 *model.Account, _a1 error) *MockDatabasePort_InsertAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabasePort_InsertAccount_Call) RunAndReturn(run func(context.Context, string) (*model.Account, error)) *MockDatabasePort_InsertAccount_Call {
	_c.Call.Return(run)
	return _c
}

// IsAccountExists provides a mock function with given fields: ctx, accountID
func (_m *MockDatabasePort) IsAccountExists(ctx context.Context, accountID string) (bool, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for IsAccountExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabasePort_IsAccountExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccountExists'
type MockDatabasePort_IsAccountExists_Call struct {
	*mock.Call
}

// IsAccountExists is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockDatabasePort_Expecter) IsAccountExists(ctx interface{}, accountID interface{}) *MockDatabasePort_IsAccountExists_Call {
	return &MockDatabasePort_IsAccountExists_Call{Call: _e.mock.On("IsAccountExists", ctx, accountID)}
}

func (_c *MockDatabasePort_IsAccountExists_Call) Run(run func(ctx context.Context, accountID string)) *MockDatabasePort_IsAccountExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabasePort_IsAccountExists_Call) Return(_a0 bool, _a1 error) *MockDatabasePort_IsAccountExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabasePort_IsAccountExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockDatabasePort_IsAccountExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function with given fields: ctx, account
func (_m *MockDatabasePort) UpdateAccount(ctx context.Context, account *model.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabasePort_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type MockDatabasePort_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *model.Account
func (_e *MockDatabasePort_Expecter) UpdateAccount(ctx interface{}, account interface{}) *MockDatabasePort_UpdateAccount_Call {
	return &MockDatabasePort_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, account)}
}

func (_c *MockDatabasePort_UpdateAccount_Call) Run(run func(ctx context.Context, account *model.Account)) *MockDatabasePort_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Account))
	})
	return _c
}

func (_c *MockDatabasePort_UpdateAccount_Call) Return(_a0 error) *MockDatabasePort_UpdateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabasePort_UpdateAccount_Call) RunAndReturn(run func(context.Context, *model.Account) error) *MockDatabasePort_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabasePort creates a new instance of MockDatabasePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabasePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabasePort {
	mock := &MockDatabasePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
