// Code generated by mockery v2.52.3. DO NOT EDIT.

package portsmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletPort is an autogenerated mock type for the WalletPort type
type MockWalletPort struct {
	mock.Mock
}

type MockWalletPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletPort) EXPECT() *MockWalletPort_Expecter {
	return &MockWalletPort_Expecter{mock: &_m.Mock}
}

// CreateWallet provides a mock function with given fields: ctx, subwalletID
func (_m *MockWalletPort) CreateWallet(ctx context.Context, subwalletID uint32) (string, error) {
	ret := _m.Called(ctx, subwalletID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (string, error)); ok {
		return rf(ctx, subwalletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) string); ok {
		r0 = rf(ctx, subwalletID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, subwalletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletPort_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletPort_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - subwalletID uint32
func (_e *MockWalletPort_Expecter) CreateWallet(ctx interface{}, subwalletID interface{}) *MockWalletPort_CreateWallet_Call {
	return &MockWalletPort_CreateWallet_Call{Call: _e.mock.On("CreateWallet", ctx, subwalletID)}
}

func (_c *MockWalletPort_CreateWallet_Call) Run(run func(ctx context.Context, subwalletID uint32)) *MockWalletPort_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockWalletPort_CreateWallet_Call) Return(_a0 string, _a1 error) *MockWalletPort_CreateWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletPort_CreateWallet_Call) RunAndReturn(run func(context.Context, uint32) (string, error)) *MockWalletPort_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletPort creates a new instance of MockWalletPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletPort {
	mock := &MockWalletPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
