// Code generated by mockery v2.52.3. DO NOT EDIT.

package portsmocks

import (
	context "context"

	model "github.com/kriuchkov/tonbeacon/core/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOutboxMessagePort is an autogenerated mock type for the OutboxMessagePort type
type MockOutboxMessagePort struct {
	mock.Mock
}

type MockOutboxMessagePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxMessagePort) EXPECT() *MockOutboxMessagePort_Expecter {
	return &MockOutboxMessagePort_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, eventType, payload
func (_m *MockOutboxMessagePort) Publish(ctx context.Context, eventType model.EventType, payload interface{}) error {
	ret := _m.Called(ctx, eventType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.EventType, interface{}) error); ok {
		r0 = rf(ctx, eventType, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxMessagePort_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockOutboxMessagePort_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType model.EventType
//   - payload interface{}
func (_e *MockOutboxMessagePort_Expecter) Publish(ctx interface{}, eventType interface{}, payload interface{}) *MockOutboxMessagePort_Publish_Call {
	return &MockOutboxMessagePort_Publish_Call{Call: _e.mock.On("Publish", ctx, eventType, payload)}
}

func (_c *MockOutboxMessagePort_Publish_Call) Run(run func(ctx context.Context, eventType model.EventType, payload interface{})) *MockOutboxMessagePort_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.EventType), args[2].(interface{}))
	})
	return _c
}

func (_c *MockOutboxMessagePort_Publish_Call) Return(_a0 error) *MockOutboxMessagePort_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxMessagePort_Publish_Call) RunAndReturn(run func(context.Context, model.EventType, interface{}) error) *MockOutboxMessagePort_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxMessagePort creates a new instance of MockOutboxMessagePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxMessagePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxMessagePort {
	mock := &MockOutboxMessagePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
